### ISSUE TITLE
forge-oss is depricated now

### ISSUE THREAD

**Issue by naturalDesign** [augustogoncalves/forge-3leg.nodejs-template#1]
While performing `npm install` command in cloud9, got the following error message:

> WARN deprecated forge-oss@2.1.0: WARNING: The 'forge-oss' npm package is deprecated in favor of the 'forge-apis' npm package, please upgrade.

**Comment by naturalDesign** [comment]
Resolved by replacing `forge-oss` with `forge-apis` in package.json file with following execution of `npm install`.

**Comment by augustogoncalves** [comment]
I'll also fix this, thanks.
